-- Hand-written, not generated by `prisma migrate dev`'s auto-diff.
-- The auto-diff refuses outright when adding a required column to a table
-- with existing rows and no default ("There are 2 rows in this table, it is
-- not possible to execute this step") — same category of situation as the
-- PENDING -> UPCOMING enum rename, which also needed a hand-written
-- migration to avoid destructive/failing auto-generated SQL.
--
-- Existing User rows get a clearly-fake placeholder ('UNKNOWN') rather than
-- an empty string, so it reads unambiguously in the DB/admin UI as "needs a
-- real value" instead of looking like a blank-but-valid phone number.

-- Step 1: add as nullable so existing rows aren't rejected by the insert.
ALTER TABLE "User" ADD COLUMN "phone" TEXT;

-- Step 2: backfill existing rows with the placeholder.
UPDATE "User" SET "phone" = 'UNKNOWN' WHERE "phone" IS NULL;

-- Step 3: now safe to enforce NOT NULL - no row can violate it.
ALTER TABLE "User" ALTER COLUMN "phone" SET NOT NULL;
